name: Blijven leren - Key Vault Action

description: Creates an Azure Key Vault and sets policies

inputs:
  principal_id:
    description: 'Principal ID of the managed identity of the webapp'
    required: true
  azure_keyvault_name:
    description: 'Name of the Azure Key Vault'
    required: true
  azure_resource_group:
    description: 'Name of the Azure Resource Group'
    required: true
  azure_location:
    description: 'Location of the Azure Resource Group'
    required: true    

runs:
  using: "composite"
  steps:
    - name: Create/Update Key Vault
      run: |
        az keyvault create --name ${{ inputs.azure_keyvault_name }} --resource-group ${{ inputs.azure_resource_group }} --location ${{ inputs.azure_location }}
      shell: bash

    - name: Set Key Vault Policy for Managed Identity
      run: |
        az keyvault set-policy --name ${{ inputs.azure_keyvault_name }} --object-id ${{ inputs.principal_id }} --secret-permissions get list
      shell: bash
