name: Blijven leren - Key Vault Action

description: Creates an Azure Key Vault and sets policies

inputs:
  principal_id:
    description: 'Principal ID of the managed identity of the webapp'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create/Update Key Vault
      run: |
        az keyvault create --name ${{ vars.AZURE_KEYVAULT_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --location ${{ vars.AZURE_LOCATION }}

    - name: Set Key Vault Policy for Managed Identity
      run: |
        az keyvault set-policy --name ${{ vars.AZURE_KEYVAULT_NAME }} --object-id ${{ inputs.principal_id }} --secret-permissions get list

    - name: Insert GitHub Environment Secrets into Key Vault
      run: |
        for secret in $(az keyvault secret list --vault-name ${{ vars.AZURE_KEYVAULT_NAME }} --query "[].id" -o tsv); do
          secret_name=$(basename $secret)
          secret_value=$(az keyvault secret show --vault-name ${{ inputs.AZURE_KEYVAULT_NAME }} --name $secret_name --query value -o tsv)
          az keyvault secret set --vault-name ${{ inputs.AZURE_KEYVAULT_NAME }} --name $secret_name --value "$secret_value"
        done
