name: Deploy Azure Static Web App

description: Deploys an Azure Static Web App

inputs:
  azure_static_webapp_name:
    description: 'Name of the Azure Static Web App'
    required: true
  azure_resource_group:
    description: 'Name of the Azure Resource Group'
    required: true
  azure_location:
    description: 'Location of the Azure Resource Group'
    required: true
  azure_subscription_id:
    description: 'Subscription ID of the Azure Subscription'
    required: true
  app_location:
    description: 'Location of the application code'
    required: true
  output_location:
    description: 'Location of the build output'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  api_key:
    description: 'Api key of the static site'
    value: ${{ steps.get-api-token.outputs.static_api_token }}

runs:
  using: "composite"
  steps:
    - name: Create/Update Resource Group
      run: |
        az group create --name ${{ inputs.azure_resource_group }} --location ${{ inputs.azure_location }}
      shell: bash

    - name: Create/Update Static Web App
      run: |
        az staticwebapp create --name ${{ inputs.azure_static_webapp_name }} --resource-group ${{ inputs.azure_resource_group }} --location ${{ inputs.azure_location }} 
      shell: bash

    - name: Get API Token
      id: get-api-token
      run: |
        api_token=$(az staticwebapp secrets list --name ${{ inputs.azure_static_webapp_name }} --resource-group ${{ inputs.azure_resource_group }} --query "properties.apiKey" --output tsv)
        echo "static_api_token=${api_token}" >> $GITHUB_OUTPUT
      shell: bash

