name: Blijven leren - Storage Action

description: Creates an Azure Storage Account and Table Storage

inputs:
  principal_id:
    description: 'Principal ID of the managed identity of the webapp'
    required: true
  azure_storage_account_name:
    description: 'Name of the Azure Storage Account'
    required: true
  azure_resource_group:
    description: 'Name of the Azure Resource Group'
    required: true
  azure_location: 
    description: 'Location of the Azure Resource Group'
    required: true
  azure_storage_sku:
    description: 'SKU of the Azure Storage Account'
    required: true
  azure_subscription_id:
    description: 'Subscription ID of the Azure Subscription'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create/Update Storage Account
      run: |
        az storage account create --name ${{ inputs.azure_storage_account_name }} --resource-group ${{ inputs.azure_resource_group }} --location ${{ inputs.azure_location }} --sku ${{ inputs.azure_storage_sku }} --kind StorageV2
      shell: bash
      
    - name: Create/Update Table Storage Resources
      run: |
        az storage table create --name LearningResources --account-name ${{ inputs.azure_storage_account_name }} --auth-mode login
      shell: bash

    - name: Create/Update Table Storage Users
      run: |
        az storage table create --name Users --account-name ${{ inputs.azure_storage_account_name }} --auth-mode login
      shell: bash
    
    - name: Assign Storage Account Access to Web App
      run: |
        az role assignment create --assignee-object-id ${{ inputs.principal_id }} --assignee-principal-type ServicePrincipal  --role "Storage Blob Data Contributor" --scope /subscriptions/${{ inputs.azure_subscription_id }}/resourceGroups/${{ inputs.azure_resource_group }}/providers/Microsoft.Storage/storageAccounts/${{ inputs.azure_storage_account_name }}
      shell: bash