name: Blijven leren - Web App Action

description: Deploys an Azure Web App and assigns managed identity

inputs:
  azure_webapp_name:
    description: 'Name of the Azure Web App'
    required: true
  azure_webapp_publish_profile:
    description: 'Publish profile for the Azure Web App'
    required: true

outputs:
  principal_id:
    description: 'Principal ID of the managed identity'

runs:
  using: "composite"
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create/Update Resource Group
      run: |
        az group create --name ${{ vars.AZURE_RESOURCE_GROUP }} --location ${{ vars.AZURE_LOCATION }}

    - name: Create/Update App Service Plan
      run: |
        az appservice plan create --name ${{ vars.AZURE_APP_SERVICE_PLAN }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --sku {{ vars.AZURE_APP_SERVICE_SKU }} --is-linux

    - name: Create/Update Web App
      run: |
        az webapp create --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --plan ${{ vars.AZURE_APP_SERVICE_PLAN }} --runtime "DOTNET|9.0"

    - name: Assign Managed Identity to Web App
      run: |
        az webapp identity assign --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}

    - name: Get Managed Identity Principal ID
      id: get-identity
      run: |
        echo "::set-output name=principal_id::$(az webapp identity show --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --query principalId --output tsv)"

    - name: Set Storage Account Name as Environment Variable
      run: |
        az webapp config appsettings set --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --settings STORAGE_ACCOUNT_NAME=${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
