name: Deploy BlijvenLeren sites

description: Deploy BlijvenLeren site

inputs:
  azure_webapp_name:
    description: 'Name of the Azure Web App'
    required: true
  azure_resource_group:
    description: 'Name of the Azure Resource Group'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get Publish Profile
      id: get-publish-profile
      run: |
        az webapp deployment list-publishing-profiles --name ${{ inputs.azure_webapp_name }} --resource-group ${{ inputs.azure_resource_group }} --query "[?publishMethod=='MSDeploy'].publishProfile" --output tsv > publishProfile.xml

    - name: Dotnet publish
      run: |
        dotnet publish -c Release -o /BlijvenLerenApi

    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.azure_webapp_name }}
        publish-profile: publishProfile.xml
        package: /BlijvenLerenApi
            