name: Deploy BlijvenLeren sites

description: Deploy BlijvenLeren sites

inputs:
  azure_webapp_name:
    description: 'Name of the Azure Web App'
    required: true
  azure_resource_group:
    description: 'Name of the Azure Resource Group'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  azure_static_web_apps_api_token:
    description: 'Azure Static Web Apps API token'
    required: true
  dotnet_version:
    description: 'Version of .NET to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
        
    - name: Get Publish Profile
      id: get-publish-profile
      run: |
        az webapp deployment list-publishing-profiles --name ${{ inputs.azure_webapp_name }} --resource-group ${{ inputs.azure_resource_group }} --query "[?publishMethod=='MSDeploy'].publishProfile" --output tsv > publishProfile.xml
      shell: bash

    - name: Dotnet publish
      run: |
        dotnet publish -c Release -o /BlijvenLerenApi
      shell: bash

    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.azure_webapp_name }}
        publish-profile: publishProfile.xml
        package: /BlijvenLerenApi
  
    - name: Deploy Static App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.azure_static_web_apps_api_token }}
        repo_token: ${{ inputs.github_token }}
        action: "upload"
        app_location: "/BlijvenLerenWeb"
        api_location: "" 
        output_location: "wwwroot"
            