name: Deploy BlijvenLeren sites
description: Deploy BlijvenLeren site
runs:
  using: 'composite'
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Publish Profile
      id: get-publish-profile
      run: |
        az webapp deployment list-publishing-profiles --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --query "[?publishMethod=='MSDeploy'].publishProfile" --output tsv > publishProfile.xml

    - name: Dotnet publish
      run: |
        dotnet publish -c Release -o /BlijvenLerenApi

    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        publish-profile: publishProfile.xml
        package: /BlijvenLerenApi
            