name: Deploy BlijvenLeren sites
description: Deploy BlijvenLeren sites to the given environment
inputs:
  environment:
    description: 'The environment to deploy to'
    required: true
    default: 'dev'
    type: string
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        Write-Host "Restoring dependencies for projects:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -notmatch '\.Tests\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet restore $_.FullName 
        }
    - name: Build
      run: |
        Write-Host "Building projects:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -notmatch '\.Tests\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet build $_.FullName --no-restore --configuration Release
        }
    - name: Test
      run: |
        Write-Host "Running tests:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -match '\.Tests\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet test $_.FullName --verbosity normal --configuration Release
        }
    - name: publish
      run: |
        Write-Host "Publishing sites:"
            