name: Build the solution and run tests

on:
  pull_request:
    types: [opened, reopened]
    branches: 'main'
    paths-ignore:
      - '.github/**'
      
defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and test
      uses: ./.github/actions/build-and-test-action
      with:
        dotnet_version: ${{ vars.DOTNET_VERSION }}