name: Build the solution and run tests

on:
  pull_request:
    types: [opened, reopened]
    branches: 'main'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: |
        Write-Host "Restoring dependencies for projects:"
        Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet restore $_.FullName 
        }
    - name: Build
      run: |
        Write-Host "Building projects:"
        Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet build $_.FullName --no-restore --configuration Release
        }
    - name: Test
      run: |
        Write-Host "Running unittests:"
        Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.Name -match '\.Tests\.csproj$' } | ForEach-Object {           
          Write-Host "$($_.Name)"
          dotnet test $_.FullName --verbosity normal --no-build --configuration Release
        }