name: Deploy Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and test
              uses: ./.github/actions/build-and-test-action
              with:
                dotnet_version: ${{ vars.DOTNET_VERSION }}

    deployment:
        needs: build-and-test
        strategy:
            matrix:
                environment: [dev, tst, acc, prd]
        runs-on: ubuntu-latest
        environment: ${{ matrix.environment }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Deploy Web App - ${{ matrix.environment }}
              uses: ./.github/actions/deploy-action