name: Infrastructure Workflow

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
    deploy-dev:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

            - name: Deploy Api
              id: webapp
              uses: ./.github/actions/webapp-action
              with:
                azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME }}
                azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
                azure_location: ${{ vars.AZURE_LOCATION }}
                azure_app_service_plan: ${{ vars.AZURE_APP_SERVICE_PLAN }}
                azure_app_service_sku: ${{ vars.AZURE_APP_SERVICE_SKU }}
                azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
                azure_webapp_runtime: ${{ vars.AZURE_WEBAPP_RUNTIME }}

            - name: Deploy FrontEnd
              id: frontend
              uses: ./.github/actions/static-app-action
              with:
                azure_static_webapp_name: ${{ vars.AZURE_STATIC_WEBAPP_NAME }}
                azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
                azure_location: ${{ vars.AZURE_LOCATION }}
                azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                app_location: ${{ vars.STATIC_APP_LOCATION }}
                output_location: ${{ vars.STATIC_OUTPUT_LOCATION }}
                github_token: ${{ secrets.AZURE_TOKEN }}

            - name: Set API Token
              uses: ./.github/actions/update-environment-secret-action
              with:
                secret_name: STATIC_API_TOKEN
                secret_value: ${{ steps.frontend.outputs.api_key }}
                pat_token: ${{ secrets.PAT_TOKEN }}
                environment_name: dev

            - name: Deploy Key Vault
              uses: ./.github/actions/keyvault-action
              with:
                principal_id: ${{ steps.webapp.outputs.principal_id }}
                azure_keyvault_name: ${{ vars.AZURE_KEYVAULT_NAME }}
                azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
                azure_location: ${{ vars.AZURE_LOCATION }}
                azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Storage
              uses: ./.github/actions/storage-action
              with:
                principal_id: ${{ steps.webapp.outputs.principal_id }}
                azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
                azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
                azure_location: ${{ vars.AZURE_LOCATION }}
                azure_storage_sku: ${{ vars.AZURE_STORAGE_SKU }}
                azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    deploy-tst:
      needs: deploy-dev
      runs-on: ubuntu-latest
      environment: tst
      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Login to Azure
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

          - name: Deploy Api
            id: webapp
            uses: ./.github/actions/webapp-action
            with:
              azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_app_service_plan: ${{ vars.AZURE_APP_SERVICE_PLAN }}
              azure_app_service_sku: ${{ vars.AZURE_APP_SERVICE_SKU }}
              azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
              azure_webapp_runtime: ${{ vars.AZURE_WEBAPP_RUNTIME }}

          - name: Deploy FrontEnd
            id: frontend
            uses: ./.github/actions/static-app-action
            with:
              azure_static_webapp_name: ${{ vars.AZURE_STATIC_WEBAPP_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              app_location: ${{ vars.STATIC_APP_LOCATION }}
              output_location: ${{ vars.STATIC_OUTPUT_LOCATION }}
              github_token: ${{ secrets.AZURE_TOKEN }}

          - name: Set API Token
            uses: ./.github/actions/update-environment-secret-action
            with:
              secret_name: STATIC_API_TOKEN
              secret_value: ${{ steps.frontend.outputs.api_key }}
              pat_token: ${{ secrets.PAT_TOKEN }}
              environment_name: tst

          - name: Deploy Key Vault
            uses: ./.github/actions/keyvault-action
            with:
              principal_id: ${{ steps.webapp.outputs.principal_id }}
              azure_keyvault_name: ${{ vars.AZURE_KEYVAULT_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Deploy Storage
            uses: ./.github/actions/storage-action
            with:
              principal_id: ${{ steps.webapp.outputs.principal_id }}
              azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_storage_sku: ${{ vars.AZURE_STORAGE_SKU }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    deploy-acc:
      needs: deploy-dev
      runs-on: ubuntu-latest
      environment: acc
      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Login to Azure
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

          - name: Deploy Api
            id: webapp
            uses: ./.github/actions/webapp-action
            with:
              azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_app_service_plan: ${{ vars.AZURE_APP_SERVICE_PLAN }}
              azure_app_service_sku: ${{ vars.AZURE_APP_SERVICE_SKU }}
              azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
              azure_webapp_runtime: ${{ vars.AZURE_WEBAPP_RUNTIME }}

          - name: Deploy FrontEnd
            id: frontend
            uses: ./.github/actions/static-app-action
            with:
              azure_static_webapp_name: ${{ vars.AZURE_STATIC_WEBAPP_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              app_location: ${{ vars.STATIC_APP_LOCATION }}
              output_location: ${{ vars.STATIC_OUTPUT_LOCATION }}
              github_token: ${{ secrets.AZURE_TOKEN}}

          - name: Set API Token
            uses: ./.github/actions/update-environment-secret-action
            with:
              secret_name: STATIC_API_TOKEN
              secret_value: ${{ steps.frontend.outputs.api_key }}
              pat_token: ${{ secrets.PAT_TOKEN }}
              environment_name: dev

          - name: Deploy Key Vault
            uses: ./.github/actions/keyvault-action
            with:
              principal_id: ${{ steps.webapp.outputs.principal_id }}
              azure_keyvault_name: ${{ vars.AZURE_KEYVAULT_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Deploy Storage
            uses: ./.github/actions/storage-action
            with:
              principal_id: ${{ steps.webapp.outputs.principal_id }}
              azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_storage_sku: ${{ vars.AZURE_STORAGE_SKU }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    deploy-prd:
      needs: deploy-dev
      runs-on: ubuntu-latest
      environment: prd
      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Login to Azure
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

          - name: Deploy Api
            id: webapp
            uses: ./.github/actions/webapp-action
            with:
              azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_app_service_plan: ${{ vars.AZURE_APP_SERVICE_PLAN }}
              azure_app_service_sku: ${{ vars.AZURE_APP_SERVICE_SKU }}
              azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
              azure_webapp_runtime: ${{ vars.AZURE_WEBAPP_RUNTIME }}

          - name: Deploy FrontEnd
            id: frontend 
            uses: ./.github/actions/static-app-action
            with:
              azure_static_webapp_name: ${{ vars.AZURE_STATIC_WEBAPP_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              app_location: ${{ vars.STATIC_APP_LOCATION }}
              output_location: ${{ vars.STATIC_OUTPUT_LOCATION }}
              github_token: ${{ secrets.AZURE_TOKEN }}

          - name: Set API Token
            uses: ./.github/actions/update-environment-secret-action
            with:
              secret_name: STATIC_API_TOKEN
              secret_value: ${{ steps.frontend.outputs.api_key }}
              pat_token: ${{ secrets.PAT_TOKEN }}
              environment_name: dev

          - name: Deploy Key Vault
            uses: ./.github/actions/keyvault-action
            with:
              principal_id: ${{ steps.webapp.outputs.principal_id }}
              azure_keyvault_name: ${{ vars.AZURE_KEYVAULT_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Deploy Storage
            uses: ./.github/actions/storage-action
            with:
              principal_id: ${{ steps.webapp.outputs.principal_id }}
              azure_storage_account_name: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
              azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
              azure_location: ${{ vars.AZURE_LOCATION }}
              azure_storage_sku: ${{ vars.AZURE_STORAGE_SKU }}
              azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}               